apiVersion: v1
kind: Pod
metadata:
    name: pulsar-admin
spec:
    containers:
      - name: pulsar-admin
        image: quay.io/chamilton614/pulsar:latest
        command: ["sh", "-c"]
        args:
          - >
            bin/apply-config-from-env.py conf/client.conf &&
            bin/apply-config-from-env.py conf/pulsar_env.sh &&
            bin/apply-config-from-env.py conf/pulsar_tools_env.sh &&
            sleep 10000000000
        envFrom:
          - configMapRef:
                name: broker-config
        env:
          - name: webServiceUrl
            value: "http://broker:8080/"
          - name: brokerServiceUrl
            value: "pulsar://broker:6650/"
          - name: PULSAR_MEM
            value: "\"-Xms64m -Xmx128m\""
