apiVersion: v1
kind: ConfigMap
metadata:
    name: proxy-config
data:
    PULSAR_MEM: "\" -Xms64m -Xmx128m -XX:MaxDirectMemorySize=128m\""
    zookeeperServers: zookeeper
    configurationStoreServers: zookeeper
    clusterName: local
---
##
## Expose all nodes on port so that you can reach cluster from outside k8
##
apiVersion: v1
kind: Service
metadata:
    name: proxy
    labels:
        app: pulsar
        component: proxy
spec:
    type: NodePort
    ports:
      - name: http
        nodePort: 30001
        port: 8080
        protocol: TCP
      - name: tcp
        nodePort: 30002
        port: 6650
        protocol: TCP
    selector:
        app: pulsar
        component: proxy
---
##
## Proxy deployment definition
##
apiVersion: apps/v1
kind: Deployment
metadata:
    name: proxy
spec:
    # Must match template:metadata:labels
    selector:
        matchLabels:
            app: pulsar
            component: proxy
    replicas: 2
    template:
        metadata:
            labels:
                app: pulsar
                component: proxy
            annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "8080"
        spec:
            containers:
              - name: proxy
                image: quay.io/chamilton614/pulsar-all:latest
                command: ["sh", "-c"]
                args:
                  - >
                    bin/apply-config-from-env.py conf/proxy.conf &&
                    bin/apply-config-from-env.py conf/pulsar_env.sh &&
                    bin/pulsar proxy
                ports:
                  - containerPort: 8080
                
                envFrom:
                  - configMapRef:
                        name: proxy-config